manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: zephyr-apps
      url-base: https://github.com/slaterd314/zephyr-apps
  defaults:
    remote: zephyr-apps
  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v3.3.0
      import: true
    - name: kimchi-drone-control
      revision: main
  self:
    path: manifest
    
